spring:
  datasource:
    url: 'jdbc:mysql://mysql-dev.texustek.com:3306/zeus?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai'
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace